[DEFAULT]
home=/usr/people/whan/ResearchDataLab/floodMIND/running_rt/DestinE_code

[PATHS]
input_project=/nobackup_1/users/whan/floodmind/floodmind_rt/
input_general=input_general/
input_radar_knmi=knmi_radar/
input_radar_gauge_adj_knmi=knmi_radar_gauge_adj/
input_destine=ExtremesDT/
input_dgmr=DGMR/
input_blended=blended/

[RUNDATE]
year=2026
month=03
day=19
hour=18

[SETTINGS]
verbose = True              # If true, prints more information about the process
param = 228                 # Parameter number of the forecast to use. For ExtremesDT, 228 is the total precipitation.
destine_extension = grib    # The file extension of the forecast to use. For ExtremesDT, this should be grib.
gauge_adjusted = True       # If true uses the gauge adjusted radar data from KNMI, if false it uses the non-gauge adjusted radar data from KNMI
rt = True                   # If true, it uses the current datetime (rounded down to the closest 30-minutes) as the date for which to run the blending code. If false, it uses the custom date specified in the code.
timesteps = 24              # Number of timesteps * timestep interval (minutes) determines the total lead time 
timestep_interval = 30      # Minutes. What is the forecast time step
n_ens_members = 20          # Total number of ensemble members
n_ens_members_dgmr = 5      # number of ensembles generated using DGMR
weights_method = bps      # The weights method used if custom weights or machine learning weights are not used
historical_destine = False  # True   #If set to True, will use an already downloaded forecast. If set to False, a new Extremes DT forecast will be downloaded (currently does not support multi-model yet if set to false)
return_weights = False      # If set to true saves a numpy array with the weights used to make the forecast
custom_weights = False      # If set to false, uses the weights as determined by pySTEPS. If a dictionairy of weights is supplied, uses those weights
re_do_blending = False      # If set to true, re-do the blending even though there is already a blend with the current settings saved
multi_model= False          # True    # If set to true uses both ExtremesDT and IFS forecasts. Only supproted for historical forecasts for now
noise = True                # If set to true uses noise in the blending algorithm (is overwritten if machine learning weights are seleced)
probmatching = True         # If set to true uses probmatching in the blending algorithm (is overwritten if machine learning weights are seleced)
pysteps_nowcast = False     # If set to True uses the pysteps nowcast instead of the DGMR nowcast
custom_extention= None      # If a custom extention is provided, adds this custom extention to the filename at the end
use_machine_learning_weights = False #True     # If set to true, uses the machine learning algorithm to determine the weights used by the blending algorithm and surpasses any custom weights given.
#KW: if this is false where does it use the existing ml weights?
